const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

// Load contract data (address & ABI) generated by the deploy script
const contractDataPath = path.join(__dirname, "contractData.json");
let contractData = null;

try {
    if (fs.existsSync(contractDataPath)) {
        const rawData = fs.readFileSync(contractDataPath);
        contractData = JSON.parse(rawData);
    }
} catch (error) {
    console.error("Error loading contract data:", error);
}

const getProvider = () => {
    // Connect to local Hardhat network
    return new ethers.JsonRpcProvider("http://127.0.0.1:8545/");
};

const getSigner = async () => {
    const provider = getProvider();
    // Get the first account from the local node (usually the deployer)
    const signer = await provider.getSigner(); 
    return signer;
};

const getContract = async () => {
    if (!contractData) {
        throw new Error("Contract data not found. Please deploy the contract first.");
    }
    const signer = await getSigner();
    return new ethers.Contract(contractData.address, contractData.abi, signer);
};

module.exports = { getProvider, getSigner, getContract };
